// src/lib/detectDocumentType.ts
import { DOCUMENT_PROMPTS } from './prompts';

/**
 * Keywords used to validate document types
 */
const KEYWORDS: Record<keyof typeof DOCUMENT_PROMPTS, string[]> = {
  INCOME_STATEMENT: [
    "Revenue",
    "Gross Revenue",
    "Net Revenue",
    "Other Revenue",
    "Interest Revenue",
    "Rental Income",
    "Royalty Income",
    "Dividend Income",
    "Foreign Exchange Gains",
    "Gains from Investments",
    "Cost of Goods Sold (COGS)",
    "Raw Materials",
    "Direct Labor",
    "Manufacturing Overheads",
    "Freight-in",
    "Import Duties",
    "Packaging Costs",
    "Inventory Write-Downs",
    "Supplier Discounts",
    "Gross Profit",
    "Operating Expenses",
    "Selling, General, and Administrative Expenses (SG&A)",
    "Salaries and Wages",
    "Marketing and Advertising",
    "Rent and Utilities",
    "Office Supplies",
    "Insurance",
    "Travel and Entertainment",
    "Professional Fees (Legal, Consulting)",
    "Depreciation of Office Equipment",
    "Communication Expenses",
    "Research and Development (R&D)",
    "Salaries of R&D Staff",
    "Materials and Supplies for R&D",
    "Contract Research Expenses",
    "R&D Facility Costs",
    "Depreciation and Amortization",
    "Depreciation of Property, Plant, and Equipment (PPE)",
    "Amortization of Intangible Assets",
    "Accumulated Depreciation",
    "Other Operating Expenses",
    "Legal Fees",
    "Consulting Fees",
    "Restructuring Costs",
    "Impairment Charges",
    "Litigation Settlements",
    "Environmental Remediation Costs",
    "Operating Income (Operating Profit)",
    "Other Income and Expenses",
    "Interest Income",
    "Interest Expense",
    "Gain or Loss on Asset Sales",
    "Foreign Exchange Gains/Losses",
    "Investment Income",
    "Dividend Income",
    "Unrealized Gains/Losses on Securities",
    "Other Non-Operating Income",
    "Other Non-Operating Expenses",
    "Income Before Tax (Earnings Before Tax - EBT)",
    "Tax Expense",
    "Current Tax Expense",
    "Deferred Tax Expense",
    "Tax Credits",
    "Tax Adjustments",
    "Net Income (Net Profit or Net Earnings)",
    "Minority Interest",
    "Preferred Dividends",
    "Earnings Attributable to Common Shareholders",
    "Earnings Per Share (EPS)",
    "Basic EPS",
    "Diluted EPS",
    "Comprehensive Income",
    "Unrealized Gains/Losses on Available-for-Sale Securities",
    "Pension Adjustments",
    "Foreign Currency Translation Adjustments",
    "Other Comprehensive Income Items",
    "Other Potential Items",
    "Extraordinary Items",
    "Non-Recurring Items",
    "Discontinued Operations"
  ],
  BALANCE_SHEET: [
    "Assets",
    "Cash and Cash Equivalents",
    "Petty Cash",
    "Marketable Securities",
    "Short-Term Investments",
    "Accounts Receivable (AR)",
    "Trade Receivables",
    "Allowance for Doubtful Accounts",
    "Notes Receivable",
    "Inventory",
    "Raw Materials",
    "Work-in-Progress (WIP)",
    "Finished Goods",
    "Inventory Reserves",
    "Prepaid Expenses",
    "Prepaid Insurance",
    "Prepaid Rent",
    "Other Prepaid Costs",
    "Other Current Assets",
    "Advances to Suppliers",
    "Deferred Tax Assets (Current Portion)",
    "Miscellaneous Current Assets",
    "Marketable Securities",
    "Assets Held for Sale",
    "Contract Assets",
    "Biological Assets",
    "Non-Current Assets (Long-Term Assets)",
    "Property, Plant, and Equipment (PPE)",
    "Land",
    "Buildings",
    "Machinery and Equipment",
    "Vehicles",
    "Furniture and Fixtures",
    "Construction in Progress",
    "Accumulated Depreciation",
    "Intangible Assets",
    "Goodwill",
    "Patents",
    "Trademarks",
    "Copyrights",
    "Customer Lists",
    "Software Development Costs",
    "Licensing Agreements",
    "Long-Term Investments",
    "Equity Securities",
    "Debt Securities",
    "Investments in Affiliates and Associates",
    "Joint Ventures",
    "Real Estate Investments",
    "Deferred Tax Assets (Non-Current Portion)",
    "Natural Resources",
    "Mineral Rights",
    "Timberland",
    "Biological Assets",
    "Other Non-Current Assets",
    "Security Deposits",
    "Deferred Charges",
    "Environmental Liabilities",
    "Liabilities",
    "Accounts Payable (AP)",
    "Trade Payables",
    "Supplier Payables",
    "Short-Term Debt",
    "Bank Loans",
    "Commercial Paper",
    "Current Portion of Long-Term Debt",
    "Accrued Expenses",
    "Salaries and Wages Payable",
    "Interest Payable",
    "Taxes Payable",
    "Utilities Payable",
    "Deferred Revenue",
    "Unearned Revenue",
    "Dividends Payable",
    "Current Portion of Deferred Tax Liabilities",
    "Other Current Liabilities",
    "Customer Deposits",
    "Advances from Customers",
    "Miscellaneous Current Liabilities",
    "Long-Term Liabilities",
    "Long-Term Debt",
    "Bonds Payable",
    "Notes Payable",
    "Mortgage Payable",
    "Deferred Tax Liabilities (Non-Current Portion)",
    "Pension Liabilities",
    "Defined Benefit Obligations",
    "Defined Contribution Obligations",
    "Lease Obligations",
    "Capital Leases",
    "Operating Leases (Long-Term)",
    "Deferred Revenue (Long-Term Portion)",
    "Other Non-Current Liabilities",
    "Asset Retirement Obligations",
    "Deferred Compensation",
    "Contingent Liabilities",
    "Environmental Remediation Liabilities",
    "Equity (Shareholder’s Equity)",
    "Common Stock",
    "Authorized Shares",
    "Issued Shares",
    "Par Value",
    "Preferred Stock",
    "Authorized Shares",
    "Issued Shares",
    "Par Value",
    "Additional Paid-In Capital (APIC)",
    "Retained Earnings",
    "Beginning Retained Earnings",
    "Net Income",
    "Dividends Paid",
    "Prior Period Adjustments",
    "Treasury Stock",
    "Cost of Treasury Shares Acquired",
    "Shares Held in Treasury",
    "Accumulated Other Comprehensive Income (AOCI)",
    "Unrealized Gains/Losses on Available-for-Sale Securities",
    "Pension Plan Adjustments",
    "Foreign Currency Translation Adjustments",
    "Non-Controlling Interest",
    "Share Premium",
    "Revaluation Surplus (if applicable)",
    "Equity in Affiliates"
  ],
  CASH_FLOW_STATEMENT: [
    "Operating Activities",
    "Cash Inflows",
    "Cash Received from Customers",
    "Interest Received",
    "Dividends Received",
    "Cash Outflows",
    "Cash Paid to Suppliers and Employees",
    "Interest Paid",
    "Income Taxes Paid",
    "Other Operating Cash Payments",
    "Adjustments for Non-Cash Items",
    "Depreciation and Amortization",
    "Stock-Based Compensation",
    "Deferred Income Taxes",
    "Gain/Loss on Sale of Assets",
    "Impairment Charges",
    "Provision for Bad Debts",
    "Other Non-Cash Adjustments",
    "Changes in Working Capital",
    "Change in Accounts Receivable",
    "Change in Inventory",
    "Change in Accounts Payable",
    "Change in Prepaid Expenses",
    "Change in Other Current Assets/Liabilities",
    "Change in Accrued Expenses",
    "Change in Deferred Revenue",
    "Other Operating Activities",
    "Cash Paid for Legal Settlements",
    "Cash Paid for Restructuring Costs",
    "Cash Paid for Environmental Remediation",
    "Investing Activities",
    "Cash Inflows",
    "Proceeds from Sale of Property, Plant, and Equipment (PPE)",
    "Proceeds from Sale of Intangible Assets",
    "Proceeds from Sale of Investments",
    "Proceeds from Sale of Subsidiaries or Business Units",
    "Collections on Loans Made to Others",
    "Cash Outflows",
    "Purchase of Property, Plant, and Equipment (CAPEX)",
    "Purchase of Intangible Assets",
    "Purchase of Long-Term Investments",
    "Acquisition of Subsidiaries or Businesses",
    "Purchase of Investments in Affiliates and Associates",
    "Loans Made to Others",
    "Other Investing Cash Payments",
    "Other Investing Activities",
    "Capitalized Development Costs",
    "Payments for Environmental Cleanups",
    "Cash Paid for Acquisitions (Non-Cash Financing)",
    "Financing Activities",
    "Cash Inflows",
    "Proceeds from Issuance of Common Stock",
    "Proceeds from Issuance of Preferred Stock",
    "Proceeds from Issuance of Debt (Bonds, Notes)",
    "Proceeds from Borrowings",
    "Proceeds from Lease Financing",
    "Cash Outflows",
    "Repurchase of Common Stock (Treasury Stock)",
    "Repurchase of Preferred Stock",
    "Payment of Dividends",
    "Cash Dividends",
    "Stock Dividends",
    "Repayment of Debt Principal",
    "Payments for Lease Obligations",
    "Other Financing Cash Payments",
    "Other Financing Activities",
    "Cash Paid for Issuance Costs",
    "Cash Received from Equity Grants",
    "Cash Paid for Equity Grants",
    "Net Increase/Decrease in Cash",
    "Cash at Beginning of Period",
    "Cash at End of Period",
    "Supplemental Cash Flow Information",
    "Non-Cash Investing and Financing Activities",
    "Conversion of Debt to Equity",
    "Acquisition of Assets by Issuing Debt",
    "Capital Lease Commitments",
    "Stock-Based Compensation Transactions",
    "Other Non-Cash Transactions"
  ],
  FDD: [
    "Franchise Disclosure Document",
    "FDD",
    "Franchisor",
    "Franchisee",
    "Franchise Fee",
    "Royalty Fee",
    "Ad Fund Fee Percentage",
    "Territory",
    "Initial Investment",
    "Term of Agreement Years",
    "Renewal Terms",
    "Territory Protection",
    "Training Programs Included",
    "Initial Investment Range Low",
    "Initial Investment Range High",
    "Other Fees",
    "Technology Fee",
    "Local Marketing",
    "Legal Disclaimers",
    "Key Items Section",
    "Date of Issuance",
    "Business Experience of Principals",
    "Litigation History",
    "Bankruptcy",
    "Initial Fees",
    "Other Fees",
    "Estimated Initial Investment",
    "Restrictions on Sources of Products and Services",
    "Franchisee Obligations",
    "Financing",
    "Franchisor Assistance, Advertising, Computer Systems, and Training",
    "Trademarks",
    "Patents, Copyrights, and Proprietary Information",
    "Obligation to Participate in the Actual Operation of the Franchise Business",
    "Restrictions on What the Franchisee May Sell",
    "Renewal, Termination, Transfer, and Dispute Resolution",
    "Public Figures",
    "Financial Performance Representations",
    "Outlets and Franchisee Information",
    "Financial Statements",
    "Contracts",
    "Receipts"
  ],
  STATEMENT_OF_SHAREHOLDERS_EQUITY: [
    "Shareholders Equity",
    "Stockholders Equity",
    "Retained Earnings",
    "Common Stock",
    "Preferred Stock",
    "Additional Paid-In Capital",
    "Treasury Stock",
    "Comprehensive Income",
    "Paid in Capital",
    "Authorized Shares",
    "Issued Shares",
    "Par Value",
    "Issuance of Common Stock",
    "Issuance of Preferred Stock",
    "Stock Options and Warrants",
    "Number of Shares Issued",
    "Additional Paid-In Capital from Common Stock",
    "Additional Paid-In Capital from Preferred Stock",
    "Issuance of Stock Options",
    "Exercise of Stock Options",
    "Proceeds from Warrants",
    "Dividends Paid",
    "Cash Dividends",
    "Stock Dividends",
    "Property Dividends",
    "Stock Repurchases (Treasury Stock)",
    "Cost of Treasury Shares Acquired",
    "Reissuance of Treasury Shares",
    "Stock-Based Compensation",
    "Vesting of Stock Awards",
    "Expense Recognition for Stock Compensation",
    "Accumulated Other Comprehensive Income (AOCI)",
    "Unrealized Gains/Losses on Available-for-Sale Securities",
    "Pension Plan Adjustments",
    "Foreign Currency Translation Adjustments",
    "Revaluation Surplus (if applicable)",
    "Increases in Asset Valuations",
    "Decreases in Asset Valuations",
    "Changes in Ownership Interests",
    "Mergers and Acquisitions",
    "Spin-offs",
    "Asset Sales Affecting Equity",
    "Conversion of Preferred to Common Stock",
    "Other Changes in Equity",
    "Capital Contributions from Owners",
    "Capital Withdrawals by Owners",
    "Non-Controlling Interest",
    "Changes Due to Net Income Attributable to Non-Controlling Interests",
    "Dividends Paid to Non-Controlling Interests",
    "Other Changes in Non-Controlling Interests",
    "Total Comprehensive Income",
    "Cumulative Comprehensive Income",
    "Equity in Affiliates",
    "Investment in Affiliates",
    "Share of Earnings from Affiliates"
  ],
  FINANCIAL_RATIOS: [
    "Ratio",
    "Liquidity",
    "Solvency",
    "Profitability",
    "Efficiency",
    "Current Ratio",
    "Quick Ratio",
    "Debt Ratio",
    "Return on Assets",
    "Return on Equity",
    "Return on Invested Capital",
    "Inventory Turnover",
    "Receivables Turnover",
    "Asset Turnover",
    "Debt to Equity",
    "Debt to EBITDA",
    "Interest Coverage Ratio",
    "Price to Earnings",
    "Price to Book",
    "Enterprise Value",
    "EV to EBITDA",
    "EV to EBIT",
    "Revenue Growth Rate",
    "EBITDA Growth Rate",
    "Net Income Growth Rate",
    "Free Cash Flow",
    "Unlevered Free Cash Flow",
    "Levered Free Cash Flow",
    "Dividend Yield",
    "Payout Ratio"
  ]
};

/**
 * Detect document type using keywords
 */
function detectDocumentTypeByKeywords(
  content: string
): keyof typeof DOCUMENT_PROMPTS {
  const contentLower = content.toLowerCase();
  
  // For each doc type, count how many keywords appear in the content
  const matches = Object.entries(KEYWORDS).map(([type, words]) => {
    const count = words.filter((w) => contentLower.includes(w)).length;
    return { type, count };
  });

  // Sort by highest count
  const best = matches.sort((a, b) => b.count - a.count)[0];

  // If we found a doc type with at least one keyword match, use it
  if (best && best.count > 0 && best.type in DOCUMENT_PROMPTS) {
    return best.type as keyof typeof DOCUMENT_PROMPTS;
  }

  return 'INCOME_STATEMENT';
}

/**
 * Combined document type detection using both OpenAI and keyword validation
 */
export async function detectDocumentType(
  content: string
): Promise<keyof typeof DOCUMENT_PROMPTS> {
  try {
    // First, get OpenAI's prediction
    const response = await fetch('/api/detect-document-type', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ content })
    });

    if (!response.ok) {
      console.error('Error with OpenAI detection, falling back to keyword detection');
      return detectDocumentTypeByKeywords(content);
    }

    const { documentType: aiType } = await response.json();
    
    // Then, get keyword-based prediction
    const keywordType = detectDocumentTypeByKeywords(content);

    // If both methods agree, we're very confident
    if (aiType === keywordType) {
      return aiType;
    }

    // If they disagree, check keyword confidence
    const keywordConfidence = Object.prototype.hasOwnProperty.call(KEYWORDS, keywordType)
      ? KEYWORDS[keywordType].filter((word: string) => content.toLowerCase().includes(word)).length
      : 0;

    // If we have high keyword confidence (3+ matches), trust keywords over AI
    if (keywordConfidence >= 3) {
      console.log('High keyword confidence, using keyword-based type:', keywordType);
      return keywordType;
    }

    // Otherwise, trust OpenAI's prediction
    console.log('Using OpenAI prediction:', aiType);
    return aiType;

  } catch (error) {
    console.error('Error in document type detection:', error);
    // Fall back to keyword detection if API call fails
    return detectDocumentTypeByKeywords(content);
  }
}
